name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run a multi-line script
        run: ./gradlew ktlintCheck